### ISSUE TITLE
How to write characteristics with no respone?

### ISSUE THREAD

**Issue by Hu-Wentao** [scientifichackers/flutter-rx-ble#20]
when I use flutter_blue, I aways use "writeNoResponse" In write characteristics, because iOS device need do this. 
I can't found method in RxBle.

**Comment by devxpy** [comment]
That isn't implemented.

I'm curious whether there are any specific use-cases for it though.

**Comment by yiguozhen0510** [comment]
have you resolve this questions?i also got this.

**Comment by Hu-Wentao** [comment]
I give up rx_ble, use flutter_blue...
