### ISSUE TITLE
I'm waiting for BleConnectionState.connected and still getting this Exception

### ISSUE THREAD

**Issue by edsonboldrini** [scientifichackers/flutter-rx-ble#21]
Connection to device has not been initialized yet. You must call "connect()" and wait for "BleConnectionState.connected" before doing any read/write operation.
java.lang.IllegalArgumentException: Connection to device has not been initialized yet. You must call "connect()" and wait for "BleConnectionState.connected" before doing any read/write operation.
![image](https://user-images.githubusercontent.com/31242886/65076064-90c57380-d96e-11e9-9b7c-f89ba88a94a9.png)

**Comment by devxpy** [comment]
Do other operations work or is it just `discoverChars` that fails?

**Comment by edsonboldrini** [comment]
Only this operation fails. To work around this, I put a delay from 2 seconds before discoverChars, but I don't think this is the best way to finish my code.

**Comment by devxpy** [comment]
FWIW, You don't need to call this method -- you can read/write chars anyway, using the correct UUID.

**Comment by devxpy** [comment]
Also, please provide a full stacktrace.

**Comment by edsonboldrini** [comment]
> FWIW, You don't need to call this method -- you can read/write chars anyway, using the correct UUID.

Sounds nice, so I will remove my discover chars.



> Also, please provide a full stacktrace.

ASAP I will provide my stacktrace with the error. Thanks for the help!

**Comment by edsonboldrini** [comment]
Too old, already solved
