### ISSUE TITLE
Not working in Android with APK build.

### ISSUE THREAD

**Issue by joaowd** [scientifichackers/flutter-rx-ble#32]
When I install the app via APK file the bluetooth doesn't work.

**Comment by joaowd** [comment]
Fixed by creating apk from android studio

**Comment by edsonboldrini** [comment]
How you did this?

**Comment by edsonboldrini** [comment]
How you did this? I didn't get succeed in my attempt :(

**Comment by joaowd** [comment]
https://flutter.dev/docs/deployment/android#how-do-i-build-a-release-from-within-android-studio
