### ISSUE TITLE
Not working after building a release apk

### ISSUE THREAD

**Issue by edsonboldrini** [scientifichackers/flutter-rx-ble#33]
After upgranding flutter version to stable 1.12, the lib stop to work when I build apk for release.

**Comment by devxpy** [comment]
Yeah, all the projects need to be [recreated](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) and code copied over.

PR welcome.

**Comment by edsonboldrini** [comment]
Aff, is it true?

**Comment by edsonboldrini** [comment]
> Yeah, all the projects need to be [recreated](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) and code copied over.
> 
> PR welcome.

I did the ["recreated"](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects), but still don't work

**Comment by edsonboldrini** [comment]
> > Yeah, all the projects need to be [recreated](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) and code copied over.
> > PR welcome.
> 
> I did the "[recreated](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)", but still don't work

I recreated my project, not the library

**Comment by devxpy** [comment]
I meant all library projects on this orgranisation :D

**Comment by edsonboldrini** [comment]
> I meant all library projects on this organisation :D

Dude! How can I start?? Should I start from where??

**Comment by timmy-gzw** [comment]
I also encountered this problem, after I built apk, Rxble not work

**Comment by edsonboldrini** [comment]
`MissingPluginException(No implementation found for ...)`

This is the error with all method calls :(

**Comment by edsonboldrini** [comment]
Too old, now working

**Comment by MazenCoder** [comment]
I also encountered this problem, after I built apk, Rxble not work

(No implementation found for method scanOnListen on channel com.pycampers.rx_ble)
