### ISSUE TITLE
BleCharacteristicNotFoundException (BleCharacteristicNotFoundException: Characteristic not found  

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [scientifichackers/flutter-rx-ble#36]
I just started a project and want to use rx-ble as it supports background bluetooth (unlike flutter_blue) with flutter_blue I could successfully read from a device, but with rx-ble I always get:

BleCharacteristicNotFoundException (BleCharacteristicNotFoundException: Characteristic not found with UUID 6bbf166d-12bf-4a33-8c8e-b24bd8b526e6

Code:

```dart
  await RxBle.stopScan();
  await for (final scanResult in RxBle.startScan()) {
  if (scanResult != null) {
    var name = "";
    try {
      name = scanResult.deviceName;
    } catch (e) {}
    if (name == null) name = scanResult.deviceId;

    if (name == "babypillow") {
      if (connect) {
        serverPrint("connect " + scanResult.deviceId + name);
        await for (final connectionState in RxBle.connect(scanResult.deviceId, waitForDevice: true, autoConnect: true)) {
          serverPrint("is connectd " + (connectionState == BleConnectionState.connected).toString());

          if (connectionState == BleConnectionState.connected) {
            //var services = await (RxBle.discoverChars(scanResult.deviceId));
            //serverPrint("serivces " + services.toString());
            await Future.delayed(Duration(seconds: 2));
            await for (var value in RxBle.observeChar(scanResult.deviceId, "6bbf166d-12bf-4a33-8c8e-b24bd8b526e6")) {
              serverPrint(value);
            }
          }
        }
      }
    }
  }
}   
```

RxBle.discoverChars(scanResult.deviceId) finds the ID and I can even read it with Flutter_blue. But with RXBle

RxBle.observeChar(scanResult.deviceId, "6bbf166d-12bf-4a33-8c8e-b24bd8b526e6")

fails with the Exception mentioned above. Any idea?

**Comment by devxpy** [comment]
Does `readChar()` work?

**Comment by TobiasHeidingsfeld** [comment]
readChar() also does not work

**Comment by TobiasHeidingsfeld** [comment]
The Characteristic is even int the Map returned by the commented out code 

`RxBle.discoverChars(scanResult.deviceId)`

**Comment by devxpy** [comment]
Can you share that aforementioned Map?

**Comment by devxpy** [comment]
Might be related - https://github.com/Polidea/RxAndroidBle/issues/559

Can you try to use [NRF connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en_IN) app and see what UUID it reports?

**Comment by TobiasHeidingsfeld** [comment]
It contains an entry {1800: [2A00, 2A01, 2A04, 2AA6], 1801: [2A05], 6bbf166d-12bf-4a33-8c8e-b24bd8b526e6: [6bbf166f-12bf-4a33-8c8e-b24bd8b526e6]}

**Comment by TobiasHeidingsfeld** [comment]
NRF connect also finds this UUID as an "Unkown Service" with Notify, Read, Write

**Comment by TobiasHeidingsfeld** [comment]
The same UUID appears in the "Unkown Characteristic" in the "Unkown Service". Let me know if you need any other information

**Comment by TobiasHeidingsfeld** [comment]
I do not understand if there is any actionable advice in the linked [stackoverflow](https://stackoverflow.com/questions/55392077/blecharacteristicnotfoundexception-characteristic-not-found-with-uuid-how-can) for me as it relates to base libary in Java/Kotlin

**Comment by devxpy** [comment]
Nrf connect doesn't report the exact UUID? 

What device are you trying to connect to? 

If it's something you built your self, maybe you can obtain the (presumably) 16-bit UUID from the device code?

**Comment by TobiasHeidingsfeld** [comment]
Nrf  does find the exact UUID as an "Unkown Characteristic" in the "Unkown Service".

The device comes from a client. They send me this UUID.

**Comment by devxpy** [comment]
You seem to have provided `6bbf166d-12bf-4a33-8c8e-b24bd8b526e6` to readChar(), but your later comment reports the characteristic UUID as `6bbf166f-12bf-4a33-8c8e-b24bd8b526e6`. 

[readChar() expects the characteristic UUID, not the service UUID](https://github.com/Polidea/RxAndroidBle/issues/559#issuecomment-477483615).

**Comment by TobiasHeidingsfeld** [comment]
@devxpy Thank you, my bad as the UUID's are almost the same
